import './styles.less';
import './images/apple-touch-icon.png';
import './images/mstile-150x150.png';
import './images/apple-touch-icon.png';
import './images/android-chrome-512x512.png';
import './images/android-chrome-192x192.png';
import './images/favicon-32x32.png';
import './images/favicon.ico';
import './images/favicon-16x16.png';
import './site.webmanifest';
import "./scripts/game.js";
console.clear();
